Handlers for Smart Connector UIExtension
eclipse-glsp/glsp-server-node pull request #70
Opened 2023-11-30 15:00 UTC by yentelmanero

This PR is part of my bachelor research conducted in TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/).

---

In this PR, the ActionHandler and ContextActionProvider as well as the related workflow example implementations for the Smart Connector UIExtension are included (more info on Smart Connector in Client PR)

[Client PR](https://github.com/eclipse-glsp/glsp-client/pull/308)
[Theia PR](https://github.com/eclipse-glsp/glsp-theia-integration/pull/188)

2023-12-19 13:02 UTC, haydar-metin commented
Thanks for the PR! I will test it after the changes are done!

You also have some compile time errors: https://github.com/eclipse-glsp/glsp-server-node/pull/70/checks?check_run_id=19184096609

Can you also add some description to your PR and reference the other PRs you have created, something like:

```
This PR is part of my bachelor research conducted in TU Wien in the [Business Informatics Group](https://www.big.tuwien.ac.at/).

---

<Little Description>

<Other PR references>
```

2023-12-19 13:06 UTC, haydar-metin requested changes

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/di/diagram-module.ts
>      }
```suggestion
    protected bindSmartConnectorItemProvider(): BindingTarget<SmartConnectorItemProvider> | undefined {
        return DefaultSmartConnectorItemProvider;
    }
    
    protected bindCommandPaletteActionProvider(): BindingTarget<CommandPaletteActionProvider> | undefined {
        return undefined;
    }
```

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-action-handler.ts
> + ********************************************************************************/
```suggestion
/********************************************************************************
 * Copyright (c) 2023 Business Informatics Group (TU Wien) and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/
```

2023-12-19 13:06 UTC, haydar-metin commented on examples/workflow-server/src/common/provider/workflow-smart-connector-item-provider.ts
> + ********************************************************************************/
```suggestion
/********************************************************************************
 * Copyright (c) 2023 Business Informatics Group (TU Wien) and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/
```

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> + ********************************************************************************/
```suggestion
/********************************************************************************
 * Copyright (c) 2023 Business Informatics Group (TU Wien) and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the Eclipse
 * Public License v. 2.0 are satisfied: GNU General Public License, version 2
 * with the GNU Classpath Exception which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 ********************************************************************************/
```
```

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +    abstract edgeTypes: Record<string, string>;
I think 

```ts
    /** filter that excludes nodes/edges from options, given a node ID as key */
    abstract nodeOperationFilter: Record<string, string[]>;
    /** edge that is used between source and destination by default when a new node is created
     *  (if not given, no edge will be created when creating new node) */
    abstract defaultEdge: string;
    /** list of edges where the key is a node ID and the value is a edge ID
     *  the edge to a new node when the source node has the ID of the key
     *  otherwise, the default edge will be used */
    abstract edgeTypes: Record<string, string>;
```

can be moved to `DefaultSmartConnectorItemProvider` (with new types)

```ts
    /** filter that excludes nodes/edges from options, given a node ID as key */
    protected nodeOperationFilter: Record<string, string[] | undefined> = {};

    /** edge that is used between source and destination by default when a new node is created
     *  (if not given, no edge will be created when creating new node) */
    protected defaultEdge?: string;

    /** list of edges where the key is a node ID and the value is a edge ID
     *  the edge to a new node when the source node has the ID of the key
     *  otherwise, the default edge will be used */
    protected edgeTypes: Record<string, string?> = {};
```

because a different implementation of `SmartConnectorItemProvider` can be created without using those.

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +        const includedInNodeFilter = (e: string): boolean => this.nodeOperationFilter[selectedNodeType].includes(e);
The `this.nodeOperationFilter[selectedNodeType].includes(e)` part can cause an error if the `selectedNodeType` does not exist in `nodeOperationFilter`. Check the updated types provided before.

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +        const includedInNodeFilter = (e: string): boolean => this.nodeOperationFilter[selectedNodeType].includes(e);
Solution could be something like `!!this.nodeOperationFilter[selectedNodeType]?.includes(e)`

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +                console.warn('Not all elements have icons. Labels will be shown, check settings for smart connector.');
Please check the code if there is already somewhere a logger and use it instead of writing directly to `console`.

2023-12-19 13:06 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +        if (showOnly === SmartConnectorGroupUIType.Labels) {paletteItems.forEach(paletteItem => paletteItem.icon = '');}
```suggestion
        if (showOnly === SmartConnectorGroupUIType.Icons) {
            if (paletteItems.every(paletteItem => paletteItem.icon !== '')) {
                console.warn('Not all elements have icons. Labels will be shown, check settings for smart connector.');
                return paletteItems;
            }
            paletteItems.forEach(paletteItem => paletteItem.label = '');
        } else if (showOnly === SmartConnectorGroupUIType.Labels) {
            paletteItems.forEach(paletteItem => paletteItem.icon = '');
        }
```

2024-01-10 14:57 UTC, haydar-metin reviewed
LGTM, just small changes

2024-01-10 14:57 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +    @inject(OperationHandlerRegistry) operationHandlerRegistry: OperationHandlerRegistry;
```suggestion
    @inject(OperationHandlerRegistry) protected operationHandlerRegistry: OperationHandlerRegistry;
```

2024-01-10 14:57 UTC, haydar-metin commented on examples/workflow-server/src/common/provider/workflow-smart-connector-item-provider.ts
> +    override nodeOperationFilter = {
```suggestion
    protected override nodeOperationFilter = {
```

2024-01-10 14:57 UTC, haydar-metin commented on examples/workflow-server/src/common/provider/workflow-smart-connector-item-provider.ts
> +    override defaultEdge = DefaultTypes.EDGE;
```suggestion
    protected override defaultEdge = DefaultTypes.EDGE;
```

2024-01-10 14:57 UTC, haydar-metin commented on examples/workflow-server/src/common/provider/workflow-smart-connector-item-provider.ts
> +    override edgeTypes = {
```suggestion
    protected override edgeTypes = {
```

2024-01-10 14:57 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +    createSmartConnectorGroupItem(handlers: CreateOperationHandler[], kind: string, selectedNodeType: string,
```suggestion
    protected createSmartConnectorGroupItem(handlers: CreateOperationHandler[], kind: string, selectedNodeType: string,
```

2024-01-10 14:57 UTC, haydar-metin commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +    create(action: PaletteItem.TriggerElementCreationAction, label: string, nodeType: string): PaletteItem | SmartConnectorNodeItem {
```suggestion
    protected create***(action: PaletteItem.TriggerElementCreationAction, label: string, nodeType: string): PaletteItem | SmartConnectorNodeItem {
```

Please provide for * a specific name, what are you creating here? `createSmartConnectorItem` probably?

2024-02-01 22:00 UTC, yentelmanero commented
Did not mean to mention that PR with that last commit

2024-03-25 08:38 UTC, tortmayr requested changes
Thanks, in general the code looks good to me.
I have a few inline comments/suggestions.
As discussed offline we like to have a more generic `SelectionPaletteProvider` API instead of the `SmartConnectorAPI`. Please rename the artifacts accordingly.

Other than that the change works really well!

2024-03-25 08:38 UTC, tortmayr commented on examples/workflow-server/src/common/provider/workflow-smart-connector-item-provider.ts
> +        [ModelTypes.AUTOMATED_TASK]: [ModelTypes.WEIGHTED_EDGE, ModelTypes.AUTOMATED_TASK, ModelTypes.MANUAL_TASK,
This could be handled generically. All the required information is present in the typehints of the `DiagramConfiguration`.
Could be moved up to the `DefaultSmartConnectorProvider`.

I don't expect that this is handled with this PR but we should create a follow-up for that.

2024-03-25 08:38 UTC, tortmayr commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +export abstract class SmartConnectorItemProvider implements ContextActionsProvider {
As discussed offline we would like to use a more generic `SelectionPaletteProvider` API (that is inline with CommandPaletteProvider and ToolpaletteProvider) and the current `SmartConnector` is then just the default implementation of that provider.
So please rename this to `SelectionPaletteProvider`.

2024-03-25 08:38 UTC, tortmayr commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +export class DefaultSmartConnectorItemProvider extends SmartConnectorItemProvider {
```suggestion
export class DefaultSelectionPaletteProvider` extends SelectionPaletteProvider {
```

2024-03-25 08:38 UTC, tortmayr commented on packages/server/src/common/features/contextactions/smart-connector-item-provider.ts
> +        return 'smart-connector';
```suggestion
        return 'selection-palette';
```

2024-03-25 08:38 UTC, tortmayr commented on packages/server/src/common/gmodel/gmodel-create-node-operation-handler.ts
> +            // Creates default edge on node creation when a source ID is given in the CreateNodeOperation
I understand why this is done this way, but we should find a more generic solution here.

Ideally we would dispatch a `CompoundOperation` on the client-side that contains the `CreateNode` and `CreateEdge` operations. Currently the API does not support this, because we need context-specific information. i.e. the `CreateEdge` operation needs to know the id of the newly created node it should connect to.

We should create a follow-up for that.

2024-03-25 08:38 UTC, tortmayr commented on packages/server/src/common/features/contextactions/smart-connector-action-handler.ts
> +export class OpenSmartConnectorActionHandler implements ActionHandler {
This should be handled entirely on client side.
The server should only provide the `selection palette actions` via the `RequestContextActions` handler but should not need to know any other implementation details about how they will be handled/rendered on the client side.

2024-03-25 08:38 UTC, tortmayr commented on packages/server/src/common/di/diagram-module.ts
> +        binding.add(OpenSmartConnectorActionHandler);
Should be handled on client side

2024-04-24 10:25 UTC, tortmayr commented
@yentelmanero 
Thank your for this awesome contribution.
I have reviewed and tested the changes. Everything seems to work as expected and all review comments have been addressed.
Nice work!

We will keep this PR open and merge it after the 2.2.0 Release is done (end of May). This way we have a full release cycle to polish the feature and address follow-up issues before we are shipping it to adopters.

In any case, from our side this concludes the practical aspect of your bachelor thesis. We don't require/desire any more changes from your side. Congrats!

2024-04-24 10:26 UTC, tortmayr approved these changes

2025-09-07 21:22 UTC, closed without merging