GLSP-1266 Fix handling of zero values in GBoundsAwareBuilder functions
eclipse-glsp/glsp-server-node pull request #76
Opened 2024-02-21 14:24 UTC by ndoschek

#### What it does

Fix handling of zero values in GBoundsAwareBuilder functions 

Resolves GH-1266

#### Changelog

- [x] This PR should be mentioned in the changelog
- [ ] This PR introduces a breaking change (if yes, provide more details below for the changelog and the migration guide)

2024-02-21 14:57 UTC, tortmayr requested changes
Looks good to me. Could you please also make the same adjustment for the `GAlignableBuilder` functions?
Also please update the `Resolves` comment in your commit to `Resolves  eclipse-glsp/glsp/issues/1266` otherwise autoclosing on merge won't work.

2024-02-21 16:11 UTC, ndoschek commented
Sure, thanks for the review @tortmayr!

2024-02-21 19:10 UTC, ndoschek commented
I found some motivation and added a few unit tests for the functions I updated, would be great if you could have a quick look on those as well when you get a chance. Thanks!

2024-02-22 11:59 UTC, tortmayr approved these changes
Thanks. More test coverage is always appreciated 😉

2024-02-22 13:35 UTC, merged